---

- hosts: all
  become: true

  tasks:
    - name: Import Vars
      include_vars:
        file: group_vars/main.yml

    - name: symlink /usr/bin/python -> /usr/bin/python3
      raw: |
        if [ -f /usr/bin/python3 ] && [ ! -f /usr/bin/python ]; then
          ln --symbolic /usr/bin/python3 /usr/bin/python; 
        fi

    - name: dependa install
      become: true
      import_tasks: imports/dependa.yml
      tags: [ dependas ]

    - name: Chrony Setup
      become: true
      import_tasks: imports/chronyd.yml
      tags: [ ntp, chrony ]

    - name: Install WTG
      include_tasks: includes/wtg.yml
      tags: [ wtg ]

    - name: Users
      include_tasks: includes/user_setup.yml
      tags: [ users ]
